[package]
name = "tun-intercept-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tun = "0.10.1"
async-std = "1.12.0"
etherparse = "0.12.0"