[package]
name = "malwarewall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tun = "0.10.1"
async-std = "1.12.0"
etherparse = "0.12.0"
mac_address = "1.1.4"
lazy_static = "1.4.0"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.17"
serde_json = "1.0.94"
cidr = { version = "0.2.1", features = ["serde"] }
log = "0.4"
pretty_env_logger = "0.4"