filters:
  # Redirect module
  redirect:
    - from_ip: 8.8.8.8
      to_ip: 1.1.1.1
      chance: 1
    - from_ip: 0.0.0.0/0
      to_honeypot: honeypots
      from_port: 22
      chance: 0.1
  # Blacklist module
  filterlist:
    - allow: true
      ip: 192.168.1.1/24
    - ip: 192.168.1.100
    - port: 22
    - port: 23
  # Rate limiting module
  rate_limit:
    # Period to check IPs in miliseconds
    period: 10000
    # Connections from the same source IP
    host_connections: 20
    # Connections from the same source IP to the same destination port
    host_port_connections: 5
    # Connections from the same source IP to the same destination IP
    host_dst_connections: 10
    # Period to check TCP connections in miliseconds
    tcp_period: 100
    # Simultaneous handshakes from the same source IP in the same period
    tcp_handshakes: 5
  suricata:
    log_path: suricatalogs/eve.json
  dns:
    - regex: ".*\\.xyz"
      allow: false
    - regex: "(.*\\.)?vut(br)?\\.cz"
      allow: false
honeypots:
  - name: honeypots
    docker_image: justsky/honeypots
    command: ["--setup", "all"]