filters:
  # Blacklist module
  blacklist:
    - 192.168.1.1/24
  whitelist:
    - 192.168.1.100
  # Redirect module
  redirect:
    - src_ip: 8.8.8.8
      dst_ip: 1.1.1.1
      chance: 1
    - src_ip: 0.0.0.0/24
      dst_ip: 10.0.0.1
      src_port: 22
      dst_port: 2222
      chance: 0.2
  # Rate limiting module
  rate_limit:
    # Period to check in miliseconds
    - period: 10000
    # Connections from the same source IP
    - host_connections: 10
    # Connections from the same source IP to the same destination port
    - host_port_connections: 5
    # Connections from the same source IP to the same destination IP
    - host_dst_connections: 5