filters:
  # Blacklist module
  filterlist:
    - allow: true
      ip: 192.168.1.1/24
    - ip: 192.168.1.100
    - port: 22
    - port: 23
  # Redirect module
  redirect:
    - from_ip: 8.8.8.8
      to_ip: 1.1.1.1
      chance: 1
    - from_ip: 0.0.0.0/0
      to_ip: 172.17.0.2 # Cowrie honeypot
      from_port: 22
      to_port: 2222
      chance: 0.1
  # Rate limiting module
  rate_limit:
    # Period to check IPs in miliseconds
    period: 10000
    # Connections from the same source IP
    host_connections: 10
    # Connections from the same source IP to the same destination port
    host_port_connections: 5
    # Connections from the same source IP to the same destination IP
    host_dst_connections: 5
    # Period to check TCP connections in miliseconds
    tcp_period: 100
    # Simultaneous handshakes from the same source IP in the same period
    tcp_handshakes: 1